---
title: "ichart"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ichart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(wastewater)
normalize = TRUE
Lim_Min = 4
virus = "SC2_N"
```

```{r}

full_dataset = presaved_data
plants = "Los Angeles, CA"
cur_subset =
    full_dataset |>
    filter(
      Plant %in% plants
    )

y_var_name =
    virus |>
    paste(
      sep = "_",
      if_else(
        normalize,
        measures[2],
        measures[1]))

chart1 = 
          cur_subset |>
        dplyr::mutate(
          date = Collection_Date,
          Dot = .data[[y_var_name]]
        ) |>
        shewhart.hybrid::I_Chart(
          Lim_Min = Lim_Min |> ceiling(),
          extra_vars = names(full_dataset),
          verbose = TRUE
          ) |>
        suppressWarnings()
```


```{r}

chart1 |>
    shewhart.hybrid::plot_run_chart(
      yvarname = "Dot",
      # marker_size = NULL,
      point_name = ifelse(normalize,
                          "Ratio of SARS-CoV-2 to PMMoV",
                          "copies per gram"),
     verbose = TRUE)
```

